### ISSUE TITLE
Errors while compiling with webpack

### ISSUE THREAD

**Issue by abombelli** [amazingSurge/jquery-wizard#11]
Hello

When compiling with webpack we get an error regarding the quotes:

/js/app.js from UglifyJs
Unexpected character '`' [./node_modules/jquery-wizard/dist/jquery-wizard.es.js:23,0][/js/app.js:83970,13]

/js/app.js from UglifyJs
Unexpected token: name (support) [./node_modules/jquery-wizard/dist/jquery-wizard.es.js:94,0][/js/app.js:84041,4]

The first one is easy done.
The second one I have no clue :-(

Any idea?

Thanks
Aldo

**Comment by amazingSurge** [comment]
Hi,
The es6 script not working well with uglifyjs.

See
https://github.com/webpack/webpack/issues/2545
