### ISSUE TITLE
npm package "jquery-wizard"

### ISSUE THREAD

**Issue by kflorence** [amazingSurge/jquery-wizard#6]
Hello! Would it be possible for you to publish your NPM package under a different name than "jquery-wizard"? This name is already taken for my project: https://github.com/kflorence/jquery-wizard (which has existed since Feb 15, 2011) -- unfortunately at the time my project was written, NPM was still in it's infancy. I had reserved the name on Bower, but now that Bower is being deprecated in favor of NPM I would prefer to publish it there under the same name.

I hope you will consider publishing your package under the same name as you have on Bower. Thanks!

**Comment by amazingSurge** [comment]
Sorry. The name is public to our clients. If i change it to another name will casing lots issues.

**Comment by kflorence** [comment]
By the way, I will also consider renaming my project to `jquery-ui-wizard`, since it relies on jQuery UI Core and Widget. If I end up renaming it, I will deprecate the current bower package and you can take it over after some time.

**Comment by amazingSurge** [comment]
Thanks for the suggestion. Since this plugin is included in our [template](
http://getbootstrapadmin.com/remark/base/forms/wizard.html), there are 4k customer relied on this plugin. If i rename it to the new name will causing unpredicted issue. If you can use another name that would be much appreciated.

**Comment by kflorence** [comment]
@amazingSurge I forgot that you can namespace packages on NPM, so I've done that: https://www.npmjs.com/package/@kflorence/jquery-wizard

Thanks for your patience. Happy new year!

**Comment by amazingSurge** [comment]
Happy new year!
